version: '3.9'
services:
  core:
    image: ghcr.io/findy-network/findy-agent:latest
    volumes:
      - .data/agent:/root
    environment:
      FCLI_POOL_GENESIS_TXN_FILE: ''
      FCLI_POOL_NAME: 'FINDY_FILE_LEDGER'
      FCLI_AGENCY_POOL_NAME: 'FINDY_FILE_LEDGER'
      FCLI_STEWARD_POOL_NAME: 'FINDY_FILE_LEDGER'
      FCLI_AGENCY_STEWARD_DID: 'Th7MpTaRZVRYnPiabds81Y'
      FCLI_STEWARD_SEED: '000000000000000000000000Steward1'
      FCLI_IMPORT_WALLET_FILE: ""
      FCLI_IMPORT_WALLET_NAME: ""
      FCLI_AGENCY_HOST_PORT: 8088
      FCLI_AGENCY_SERVER_PORT: 8088
    #      FCLI_LOGGING: '-logtostderr -v=9 -vmodule=cmdHandles=10,agency*=15,agent*=15'
    ports:
      - '8080:8080'
      - '50052:50051'

  auth:
    image: ghcr.io/findy-network/findy-agent-auth:latest
    volumes:
      - .data/auth:/data
    depends_on:
      - core
    environment:
      FAA_ENABLE_CORS: 'true'
      FAA_ORIGIN: 'http://localhost:3000'
      FAA_AGENCY_ADDR: 'core'
      FAA_CERT_PATH: ''
      FAA_AGENCY_INSECURE: "true"
    ports:
      - '8088:8888'

  vault:
    image: ghcr.io/findy-network/findy-agent-vault:latest
    depends_on:
      - vault-db
      - core
    environment:
      FAV_DB_PASSWORD: 'password'
      FAV_AGENCY_HOST: 'core'
      FAV_AGENCY_CERT_PATH: ''
      FAV_AGENCY_INSECURE: 'true'
    ports:
      - '8085:8085'

  vault-db:
    image: postgres:13.6-alpine
    volumes:
      - .data/vault-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'vault'
      POSTGRES_PASSWORD: 'password'

  pwa:
    build:
      context: ../..
      dockerfile: ./tools/env-docker/Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - vault
